import { BRAND } from '../config/brand';
import type { EntryView } from '../data/repositories/entries';
import type { MessageRecord } from '../data/types';
import { formatDate, formatDateTime } from '../utils/dates';
import { slugify } from '../utils/text';

export function sourceName(source: string): string {
  return source === 'chatgpt' ? 'ChatGPT' : source === 'claude' ? 'Claude' : source;
}

export function speakerName(m: Pick<MessageRecord, 'role' | 'authorName'>, source: string): string {
  switch (m.role) {
    case 'user':
      return 'You';
    case 'assistant':
      return sourceName(source);
    case 'tool':
      return m.authorName ? `Tool · ${m.authorName}` : 'Tool';
    case 'system':
      return 'System';
    default:
      return 'Unknown';
  }
}

function msgRefs(ids: string[], byId: Map<string, MessageRecord>): string {
  const nums = ids.map((id) => byId.get(id)?.index).filter((n): n is number => n !== undefined).map((n) => n + 1);
  if (nums.length === 0) return '';
  return ` _(message${nums.length > 1 ? 's' : ''} ${nums.join(', ')})_`;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Markdown export. Derived (AI/sample) sections are labelled; the transcript is verbatim. */
export function entryToMarkdown(view: EntryView, now = new Date()): string {
  const { entry, conversation, messages, images } = view;
  const byId = new Map(messages.map((m) => [m.id, m]));
  const out: string[] = [];
  out.push(`# ${entry.title}`);
  if (entry.subtitle) out.push('', `_${entry.subtitle}_`);
  out.push(
    '',
    `- **Source:** ${sourceName(entry.source)}${conversation ? ` (conversation ${conversation.sourceConversationId})` : ''}`,
    `- **Date:** ${formatDate(entry.chatDate)} · ${entry.messageCount} messages · ${entry.imageCount} images`,
  );
  if (entry.tags.length) out.push(`- **Tags:** ${entry.tags.join(', ')}`);
  if (view.collection) out.push(`- **Collection:** ${view.collection.name}`);
  out.push(`- **Exported:** ${formatDateTime(now.toISOString())} from ${BRAND.name}`);

  if (images.length) {
    out.push('', '## Images', '');
    images.forEach((img, i) => {
      const from = img.messageId && byId.get(img.messageId) ? ` — message ${byId.get(img.messageId)!.index + 1}` : '';
      const name = img.title ?? img.originalFilename ?? `Image ${i + 1}`;
      out.push(`${i + 1}. **${name}**${from}${img.available ? '' : ' _(not included in the export)_'}`);
      if (img.prompt) out.push(`   - ${img.promptKind === 'user_request' ? 'Requested in' : 'Prompt'}: ${img.prompt.replace(/\s+/g, ' ')}`);
    });
  }

  out.push('', '## Summary', '');
  if (entry.summaryStatus === 'complete' || entry.summary) {
    out.push(entry.summary);
    if (entry.summaryProvider) out.push('', `_Generated by ${entry.summaryProvider}${entry.summaryGeneratedAt ? ` on ${formatDate(entry.summaryGeneratedAt)}` : ''}._`);
  } else {
    out.push('_Summary not generated._');
  }

  if (entry.keyDecisions.length) {
    out.push('', '## Key decisions', '');
    for (const d of entry.keyDecisions) out.push(`- ${d.text}${msgRefs(d.sourceMessageIds, byId)}`);
  }
  if (entry.nextSteps.length) {
    out.push('', '## Next steps', '');
    for (const d of entry.nextSteps) out.push(`- [ ] ${d.text}${msgRefs(d.sourceMessageIds, byId)}`);
  }
  for (const list of entry.extractedLists) {
    out.push('', `## ${list.heading}`, '', '| Item | Value |', '| --- | --- |');
    for (const r of list.rows) out.push(`| ${escapeCell(r.label)} | ${escapeCell(r.value)} |`);
  }
  const highlights = entry.highlightMessageIds.map((id) => byId.get(id)).filter((m): m is MessageRecord => !!m);
  if (highlights.length) {
    out.push('', '## Highlights', '');
    for (const m of highlights) {
      const quote = m.text.length > 600 ? `${m.text.slice(0, 600)}…` : m.text;
      out.push(`> ${quote.replace(/\n/g, '\n> ')}`, `> — ${speakerName(m, entry.source)}, message ${m.index + 1}`, '');
    }
  }

  out.push('', '## Transcript', '');
  for (const m of messages) {
    out.push(`### ${m.index + 1} · ${speakerName(m, entry.source)}${m.createdAt ? ` · ${formatDateTime(m.createdAt)}` : ''}`, '');
    out.push(m.text || '_(no text)_');
    if (m.imageIds.length) out.push('', `_${m.imageIds.length} image${m.imageIds.length > 1 ? 's' : ''} attached._`);
    if (m.attachments.length) out.push('', `_Attachments: ${m.attachments.map((a) => a.name).join(', ')}_`);
    for (const a of m.attachments) {
      if (a.extractedText) out.push('', `<details><summary>${a.name}</summary>`, '', '```text', a.extractedText, '```', '', '</details>');
    }
    out.push('');
  }
  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`;
}

/** JSON export: source data and derived data kept separate. Image binaries are not embedded. */
export function entryToJson(view: EntryView, now = new Date()): string {
  const { entry, derived, edits, conversation, messages, images, collection } = view;
  return JSON.stringify(
    {
      format: 'conversation-journal-entry',
      formatVersion: 1,
      exportedAt: now.toISOString(),
      exportedBy: `${BRAND.name} ${BRAND.version}`,
      entry: {
        id: entry.id,
        title: entry.title,
        subtitle: entry.subtitle,
        tags: entry.tags,
        collection: collection?.name ?? null,
        chatDate: entry.chatDate,
      },
      derived: {
        summary: derived.summary,
        summaryStatus: derived.summaryStatus,
        summaryProvider: derived.summaryProvider,
        summaryGeneratedAt: derived.summaryGeneratedAt,
        keyDecisions: derived.keyDecisions,
        nextSteps: derived.nextSteps,
        extractedLists: derived.extractedLists,
        highlightMessageIds: derived.highlightMessageIds,
      },
      userEdits: edits,
      source: {
        conversation,
        messages,
        images: images.map((i) => ({ ...i, binaryIncluded: false })),
      },
    },
    null,
    2,
  );
}

export function exportFileName(title: string, ext: 'md' | 'json'): string {
  return `${slugify(title)}.${ext}`;
}

export function downloadText(fileName: string, text: string, mime: string): void {
  const url = URL.createObjectURL(new Blob([text], { type: `${mime};charset=utf-8` }));
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
