import assert from 'node:assert/strict';
import fs from 'node:fs';
import type http from 'node:http';
import type { AddressInfo } from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { after, before, beforeEach, describe, it } from 'node:test';
import { entryPath, matchPath, parseHash, withQuery } from '../../src/app/router';
import { getEntryView, listEntries } from '../../src/data/repositories/entries';
import { entryToJson, entryToMarkdown } from '../../src/export/entry-export';
import { loadSampleJournal } from '../../src/fixtures/sample-journal';
import { toIso } from '../../src/utils/dates';
import { sniffImageMime } from '../../src/utils/mime';
import { slugify, truncateAtWord, uniqueTags } from '../../src/utils/text';
import { parseEnv } from '../../server/env';
import { createAppServer, CONTENT_SECURITY_POLICY } from '../../server/http';
import { callLlm, getLlmStatus, validateLlmBody } from '../../server/llm-adapter';
import { freshDb } from '../helpers/db';
import { PNG_1PX } from '../helpers/fixtures';

const ROOT = path.join(import.meta.dirname, '../..');

describe('product name is a placeholder', () => {
  it('is only defined in .env (PUBLIC_APP_NAME), never hard-coded in the app', () => {
    const name = parseEnv(fs.readFileSync(path.join(ROOT, '.env'), 'utf8')).PUBLIC_APP_NAME;
    assert.ok(name, '.env must define PUBLIC_APP_NAME');
    const pattern = new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    const offenders: string[] = [];
    const walk = (dir: string) => {
      for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, f.name);
        if (f.isDirectory()) walk(p);
        else if (/\.(tsx?|css|html|js|json|svg)$/.test(f.name) && pattern.test(fs.readFileSync(p, 'utf8'))) offenders.push(path.relative(ROOT, p));
      }
    };
    for (const dir of ['src', 'public', 'server', 'scripts']) walk(path.join(ROOT, dir));
    if (pattern.test(fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8'))) offenders.push('index.html');
    assert.deepEqual(offenders, []);
  });
});

describe('router', () => {
  it('parses hash paths and queries', () => {
    const loc = parseHash('#/entry/abc%3A1?image=i1');
    assert.equal(loc.path, '/entry/abc%3A1');
    assert.equal(loc.query.get('image'), 'i1');
    assert.deepEqual(matchPath('/entry/:id', loc.path), { id: 'abc:1' });
    assert.equal(matchPath('/entry/:id', '/search'), null);
    assert.equal(parseHash('').path, '/');
  });

  it('builds deep links', () => {
    assert.equal(entryPath('entry:chatgpt:x', { message: 'm:1' }), '/entry/entry%3Achatgpt%3Ax?message=m%3A1');
    assert.equal(withQuery('/', { source: null, tag: 'a b' }), '/?tag=a+b');
  });
});

describe('utilities', () => {
  it('normalizes export timestamps', () => {
    assert.equal(toIso(1767225600), '2026-01-01T00:00:00.000Z');
    assert.equal(toIso(1767225600000), '2026-01-01T00:00:00.000Z');
    assert.equal(toIso('2026-01-01T00:00:00Z'), '2026-01-01T00:00:00.000Z');
    assert.equal(toIso('1767225600'), '2026-01-01T00:00:00.000Z');
    assert.equal(toIso(null), null);
    assert.equal(toIso('garbage'), null);
    assert.equal(toIso(0), null);
  });

  it('text helpers', () => {
    assert.equal(truncateAtWord('The quick brown fox jumps over the lazy dog', 20), 'The quick brown fox…');
    assert.equal(slugify('Tabletop hologram — display!'), 'tabletop-hologram-display');
    assert.deepEqual(uniqueTags(['#DIY', 'diy', ' Wood Work '], 5), ['diy', 'wood work']);
  });

  it('sniffs image types from bytes', () => {
    assert.equal(sniffImageMime(PNG_1PX), 'image/png');
    assert.equal(sniffImageMime(new TextEncoder().encode('<svg xmlns="x"></svg>')), 'image/svg+xml');
    assert.equal(sniffImageMime(new Uint8Array([1, 2, 3])), null);
  });
});

describe('entry export', () => {
  beforeEach(freshDb);

  it('writes Markdown with images, labelled derived sections and the verbatim transcript', async () => {
    await loadSampleJournal();
    const entry = (await listEntries()).find((e) => e.title === 'Tabletop hologram display')!;
    const view = (await getEntryView(entry.id))!;
    const md = entryToMarkdown(view, new Date('2026-09-20T00:00:00Z'));
    assert.match(md, /^# Tabletop hologram display/);
    assert.match(md, /## Images\n\n1\. \*\*Generated image\*\*|## Images\n\n1\. \*\*/);
    assert.match(md, /Prompt: A small clear PETG pyramid/);
    assert.match(md, /_Generated by Sample data/);
    assert.match(md, /- \[ \] Print the trapezoid template/);
    assert.match(md, /\| Felt pads \| 4 \|/);
    for (const m of view.messages) assert.ok(md.includes(m.text), `transcript contains message ${m.index + 1}`);
  });

  it('writes JSON with source and derived data kept apart', async () => {
    await loadSampleJournal();
    const entry = (await listEntries()).find((e) => e.source === 'claude')!;
    const json = JSON.parse(entryToJson((await getEntryView(entry.id))!)) as Record<string, Record<string, unknown>>;
    assert.equal(json.format as unknown, 'conversation-journal-entry');
    assert.ok(Array.isArray(json.source?.messages));
    assert.equal((json.source?.messages as unknown[]).length, 10);
    assert.equal(json.derived?.summaryStatus, 'complete');
    assert.ok((json.source?.images as { binaryIncluded: boolean }[]).every((i) => i.binaryIncluded === false));
  });
});

describe('local server adapter', () => {
  it('reports status without exposing keys', () => {
    assert.equal(getLlmStatus({}).available, false);
    const s = getLlmStatus({ ANTHROPIC_API_KEY: 'sk-secret' });
    assert.deepEqual([s.available, s.vendor], [true, 'anthropic']);
    assert.ok(!JSON.stringify(s).includes('sk-secret'));
    assert.equal(getLlmStatus({ OPENAI_API_KEY: 'k', LLM_VENDOR: 'openai', OPENAI_MODEL: 'm' }).model, 'm');
    assert.equal(getLlmStatus({ LLM_VENDOR: 'openai' }).available, false);
  });

  it('validates request bodies', () => {
    assert.throws(() => validateLlmBody({ system: 1 }), /string "system" and "prompt"/);
    assert.equal(validateLlmBody({ system: 's', prompt: 'p', maxTokens: 999999 }).maxTokens, 8192);
  });

  it('calls Anthropic and OpenAI with the expected shapes', async () => {
    const seen: { url: string; body: Record<string, unknown>; headers: Record<string, string> }[] = [];
    const fake = (async (url: string, init: RequestInit) => {
      seen.push({ url, body: JSON.parse(String(init.body)), headers: init.headers as Record<string, string> });
      const payload = url.includes('anthropic') ? { content: [{ type: 'text', text: '{"a":1}' }] } : { choices: [{ message: { content: '{"b":2}' } }] };
      return new Response(JSON.stringify(payload), { status: 200 });
    }) as unknown as typeof fetch;
    const a = await callLlm({ system: 's', prompt: 'p' }, { ANTHROPIC_API_KEY: 'ka' }, undefined, fake);
    assert.equal(a.text, '{"a":1}');
    assert.equal(seen[0]?.headers['x-api-key'], 'ka');
    assert.equal(seen[0]?.body.system, 's');
    const o = await callLlm({ system: 's', prompt: 'p' }, { OPENAI_API_KEY: 'ko' }, undefined, fake);
    assert.equal(o.text, '{"b":2}');
    assert.equal(seen[1]?.headers.authorization, 'Bearer ko');
  });

  describe('http server', () => {
    let server: http.Server;
    let base = '';
    let dir = '';
    before(async () => {
      dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cj-'));
      fs.writeFileSync(path.join(dir, 'index.html'), '<!doctype html><title>t</title>');
      fs.writeFileSync(path.join(os.tmpdir(), 'secret.txt'), 'nope');
      server = createAppServer({ root: dir, env: {} });
      await new Promise<void>((r) => server.listen(0, '127.0.0.1', r));
      base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
    });
    after(() => server.close());

    it('serves the app with a restrictive CSP and SPA fallback', async () => {
      const res = await fetch(`${base}/some/deep/path`);
      assert.equal(res.status, 200);
      assert.equal(res.headers.get('content-security-policy'), CONTENT_SECURITY_POLICY);
      assert.match(CONTENT_SECURITY_POLICY, /connect-src 'self' http:\/\/localhost:\*/);
    });

    it('never serves files outside the app folder', async () => {
      const res = await fetch(`${base}/..%2Fsecret.txt`);
      const body = await res.text();
      assert.ok(!body.includes('nope'));
    });

    it('rejects API calls without the app header or from another origin', async () => {
      assert.equal((await fetch(`${base}/api/llm/status`)).status, 403);
      const foreign = await fetch(`${base}/api/llm`, {
        method: 'POST',
        headers: { 'x-journal-client': '1', origin: 'https://evil.example', 'content-type': 'application/json' },
        body: '{}',
      });
      assert.equal(foreign.status, 403);
      const ok = await fetch(`${base}/api/llm/status`, { headers: { 'x-journal-client': '1' } });
      assert.equal(ok.status, 200);
      assert.equal(((await ok.json()) as { available: boolean }).available, false);
    });

    it('returns a readable error when no key is configured', async () => {
      const res = await fetch(`${base}/api/llm`, { method: 'POST', headers: { 'x-journal-client': '1', 'content-type': 'application/json' }, body: JSON.stringify({ system: 's', prompt: 'p' }) });
      assert.equal(res.status, 503);
      assert.match(((await res.json()) as { error: string }).error, /No API key configured/);
    });
  });
});
